server:
  port: 8084
spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

auth:
  jwt:
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
