server:
  port: 8083
spring:
  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    request:
      timeout: 10s
services:
  item-service-url: http://localhost:8082
  payment-service-url: http://localhost:8084
springdoc:
  swagger-ui:
    path: /swagger-ui.html

auth:
  jwt:
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
